[book]
authors = ["eze-kiel"]
language = "en"
multilingual = false
src = "src"
title = "Open Weight Database"
description = "The free and open-source outdoor gear inventory, to help you prepare your next trip!"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/OpenWeightDatabase/OpenWeightDatabase.github.io"
git-repository-icon = "fa-github"
default-theme = "rust"
no-section-label = true
cname = "openweightdatabase.org"