[book]
authors = ["eze-kiel"]
language = "en"
multilingual = false
src = "src"
title = "Open Weight Database"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/OpenWeightDatabase/OpenWeightDatabase.github.io"
git-repository-icon = "fa-github"
default-theme = "rust"
no-section-label = true
cname = "openweightdatabase.org"